---
name: Build Latest and Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catdog

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: OpenShift Tools Installer
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4"

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1.1
        with:
          openshift_server_url: ${{ secrets.OC_SERVER }}
          openshift_token: ${{ secrets.OC_TOKEN }}
          namespace: catdog
          insecure_skip_tls_verify: true

      - name: oc-new-app
        uses: redhat-actions/oc-new-app@v1.2
        with:
          app_name: catdog-api
          image: ${{ secrets.DOCKERHUB_USERNAME }}/catdog
          port: 8000
          registry_hostname: docker.io
          registry_username: ${{ secrets.DOCKERHUB_USERNAME}}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN}}
